version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: dam_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - dam_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dam_backend
    restart: always
    ports:
      - "5001:5000"  # แก้เป็น 5000 เพราะ Flask รันที่ port 5000 ภายใน container
    depends_on:
      - mongodb
    environment:
      - BACKEND_URL=http://backend:5001
    networks:
      - dam_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dam_frontend
    restart: always
    ports:
      - "3001:3000"  # แก้เป็น 3000 เพราะ Express รันที่ port 3000 ภายใน container
    environment:
      - PORT=3000
      - BACKEND_URL=http://localhost:5001
    depends_on:
      - backend
    networks:
      - dam_network

networks:
  dam_network:
    driver: bridge

#volumes:
 # mongodb_data:
  #  name: water-level-monitor_mongodb_data